# Main proxy configuration
listen: ":8080"
admin_listen: ":8081"  # Admin server listener (TCP or /path/to/socket.sock)

# Redis configuration
redis:
  # Use either local: true or addresses for Redis connection
  local: true
  # addresses:
  #   - "redis1:6379"
  #   - "redis2:6379"
  
  # Optional Redis authentication
  # password: "mypassword"
  
  # Redis database number
  db: 0
  
  # Redis key for storing route configuration
  key: "limiting_proxy_config"
  
  # Connection pool size
  poolSize: 10
  
  # Optional Redis Sentinel configuration
  # sentinel:
  #   addresses:
  #     - "sentinel1:26379"
  #     - "sentinel2:26379"
  #   masterName: "mymaster"

routes:
  applications: []
